### ISSUE TITLE
Feature Stability Checklist

### ISSUE THREAD

**Issue by davissp14** [fly-apps/postgres-flex#72]
### Basics
- [ ]  Provisioning via `fly pg create --repmgr ...`
- [ ]  Restores: `fly pg create  --repmgr --snapshot-id  ...`
- [ ]  Horizontal scaling: `fly machines clone <machine-id>`
- [ ]  Image updates: `fly image update ...`
- [ ]  Member should be unregistered on machine removal. 

### Administrative
- [ ]  `fly pg attach`
- [ ]  `fly pg detach`
- [ ]  `fly pg connect`
- [ ]  `fly pg restart`
- [ ]  `fly pg users list`
- [ ]  `fly pg db list`
- [ ]  `fly pg failover`
- [ ]  `fly pg config show`
- [ ]  `fly pg config update`

### Other
- [ ]  Primary should automatically go readonly when disk capacity > 90%
- [ ]  Primary should automatically go readonly when quorum is lost. ( E.G. shutting down majority of nodes in a cluster )
- [ ]  Primary should read-only in the event of a network partition where all nodes stay up.
